import Head from 'next/head'
import Header from './section/Header'
import PopulerCar from './section/PopulerCar'
import Recomendation from './section/Recomendation'
import Footer from './section/Footer'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='font-jakarta'>
        <div className="bg-[#F6F7F9]">
          <Header />
          <PopulerCar />
          <Recomendation />
          <Footer />
        </div>
      </main>
    </>
  )
}
